<a href="https://colab.research.google.com/github/hardik-kumar-10/UCS420/blob/main/Assignmen4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
for i in range(len(a)):
  a[i]=a[i]+2;
print(a)

[3 4 5 6 7 8]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
for i in range(len(a)):
  a[i]=a[i]*3;
print(a)

[ 3  6  9 12 15 18]


In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6])
for i in range(len(a)):
  a[i]=a[i]/2;
print(a)

[0 1 1 2 2 3]


In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed=np.flip(arr,0)
print(reversed)

[5 4 6 3 2 1]


In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
counts = np.bincount(x)
most_frequent_value = np.argmax(counts)
indices = np.where(x == most_frequent_value)[0]

print("Most frequent value:", most_frequent_value)
print("Indices:", indices)


Most frequent value: 1
Indices: [0 5 7 8 9]


In [7]:
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
counts = np.bincount(y)
most_frequent_value = np.argmax(counts)
indices = np.where(y == most_frequent_value)[0]

print("Most frequent value:", most_frequent_value)
print("Indices:", indices)


Most frequent value: 1
Indices: [0 1 2]


In [12]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [19]:
HARDIK=np.linspace(10, 100, num=25)
print(HARDIK)
print(HARDIK.ndim)
print(HARDIK.shape)
print(HARDIK.size)
print(HARDIK.dtype)
print(HARDIK.nbytes)

transpose_Array=HARDIK.reshape(25,1)
print(transpose_Array)
print(transpose_Array.shape)


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
(25, 1)


In [25]:
ucs420_Hardik=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Hardik)
print(np.mean(ucs420_Hardik))
print(np.median(ucs420_Hardik))
print(ucs420_Hardik.max())
print(ucs420_Hardik.min())
print(np.unique(ucs420_Hardik))

reshaped_ucs420_Hardik=ucs420_Hardik.reshape(4,3)
print(reshaped_ucs420_Hardik)

resized_ucs420_Hardik = np.resize(ucs420_Hardik, (2, 3))
print(resized_ucs420_Hardik)





[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
